### PR TITLE
[BROKEN] Prepare a snap of the 0.98 release

### LINKED ISSUE #907: Roll a Snap release for 0.98
Opening an issue for the snap of the new release. It didn't work out of the box so I don't want to lose sight/track of this task!

### PR DESCRIPTION
**Pull request by lornajane**
We tagged a 0.98 release and normally I release a snap of each release (Fixes #907 or rather it would do if it worked). However this time I have run into problems. It builds fine with the changes in this branch. It also runs if no styles are used.

However with a stylesheet, I get an error about fc-match:

```
FileNotFoundError: [Errno 2] No such file or directory: 'fc-match': 'fc-match'
```

I think this is because of the issue [here on the snapcraft forums](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/71) ( warning that's quite a long discussion ) detailing a mismatch between font config versions. So far, it doesn't look like there's a fix, but I'm still asking around. So don't merge the PR but I wanted to share both my work-in-progress branch and the discussion around it.

### CODE REVIEW

**Comment by lornajane** [comment]
I'm watching all the places I think will get news if this gets fixed, for now if you're looking to install 0.98, pip is the best route, or use the 0.97 snap in the meantime.

**Comment by mgedmin** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'fc-match': 'fc-match'

This sounds like it's trying to subprocess.run(['fc-match', ...]), but you don't have a `/usr/bin/fc-match` in the environment where it's running.

You may need to install `fontconfig` inside the snap to get the fc-match binary.

**Comment by magicmonkey** [comment]
Still broken for me with the 0.98 snap; error messages attached are from running `rst2pdf --stylesheets=simple.style document1.rst` with the files from the "Document with Simple Styling" section of https://rst2pdf.org/examples.
[error.txt](https://github.com/rst2pdf/rst2pdf/files/5367271/error.txt)

**Comment by mgedmin** [comment]
And these errors look like fontconfig is too old to understand all the syntax in /etc/fonts/fonts.conf?

I think the good people in https://forum.snapcraft.io/ might be better qualified to help with this.

**Comment by lornajane** [comment]
Indeed, please see the links to the snapcraft forum in the initial description of the pull request.

**Comment by lornajane** [comment]
Closing, I can't see us working around this problem any time soon.

**Pull request closed without merging**
