### PR TITLE
futurize --stage2 (py2/3 compatibility)

### PR DESCRIPTION
**Pull request by oesteban**
(Includes #581)

Diff w.r.t. stage 1: https://github.com/oesteban/rst2pdf/compare/futurize/stage1...futurize/stage2

### CODE REVIEW

**Comment by oz123** [comment]
Great job.... Can you please consider using pip instead of conda?

**Comment by oz123** [comment]
@oesteban does this also fix https://github.com/rst2pdf/rst2pdf/issues/587?

Before I merge this, I'd like to fix #587.

**Comment by oesteban** [comment]
Ok, I'll see #587. I don't think it fixes that one, but is definitely related.

**Comment by oz123** [comment]
OK. You are fast ... Please next time, let's merge small branches. This is much easier to follow and compare. Now I'm merging 3 PRs all at once. This causes me hesitation.

**Comment by oesteban** [comment]
Sorry @oz123, I should've marked this as WIP... I'm still working on it.

**Pull request merged**
