### PR TITLE
Update ReportLab to 3.6.12

### PR DESCRIPTION
**Pull request by akrabat**
ReportLab version 3.6.5 changed something about spacing, particular for headers/footers that affected a number of tests. As I can't see anything we can directly do in our code to fix this, I've just updated the tests to accept the new rendering.

### CODE REVIEW

**Review by lornajane — APPROVED** [review]

**Comment by lornajane** [comment]
This looks good, I agree that since reportlab haven't reverted the spacing change that it's best for us to update our tests to expect it, and I've visually inspected all the PDF diffs which look correct. However we also relocated the tests directory, so could you rebase please?

We should also put in the release notes that there are some layout changes, I particularly noticed:
* header/footer spacing changes
* space before nested bullets is bigger than before
* some fully-justified text paragraphs now wrap differently

**Comment by akrabat** [comment]
Rebased against #1134 and added a note to CHANGES.rst. Will need rebasing against main after #1134 is merged.

**Comment by akrabat** [comment]
Rebased now that #1134 is merged.

**Review by lornajane — APPROVED** [review]
Still looks good after the rebase, thank you!

**Pull request merged**
