### PR TITLE
Make separations better.

### PR DESCRIPTION
**Pull request by rawsonj**
Add style support for separations.
Add color for separations.

### CODE REVIEW

**Comment by rawsonj** [comment]
I don't know what "black" is in travis-ci, or why it's reformatting flowables.py.

Can someone shed some light on why it's failing there?

**Comment by stephenfin** [comment]
black is a automatic code formatter. You can resolve the issues by using `pre-commit run -a` (after installing pre-commit, of course)

**Comment by rawsonj** [comment]
Ok, I don't get it.

When I run it, black on my side wants to modify 19 files, 18 of which I didn't touch.

When I run black against flowables.py, it modifies it, I commit it and then black on the travis side barfs.

Is there a version mismatch? WTF?

I'm on Arch if that makes a difference, but I don't see anything that should hinder this.

**Comment by stephenfin** [comment]
> Ok, I don't get it.
> 
> When I run it, black on my side wants to modify 19 files, 18 of which I didn't touch.
> 
> When I run black against flowables.py, it modifies it, I commit it and then black on the travis side barfs.
> 
> Is there a version mismatch? WTF?
> 
> I'm on Arch if that makes a difference, but I don't see anything that should hinder this.

Not a clue. I pulled it down and fixed the black issues. That should be passing now.

**Comment by rawsonj** [comment]
Cool, thanks @stephenfin!

**Review by stephenfin — APPROVED** [review]
LGTM

**Comment by akrabat** [comment]
Can we add a test that shows this working?

i.e. create a `rst2pdf/tests/input/test-separations.txt` and `rst2pdf/tests/input/test-separations.style` which demo the change. Create the test-separations.pdf and store into `rst2pdf/tests/reference`. 

`pytest` should then pass.

**Review by akrabat — CHANGES_REQUESTED** [review]
Can we add a test that shows this working?

i.e. create a `rst2pdf/tests/input/test-separations.txt` and `rst2pdf/tests/input/test-separations.style` which demo the change. Create the test-separations.pdf and store into `rst2pdf/tests/reference`. 

`pytest` should then pass.

**Comment by rawsonj** [comment]
@stephenfin Man, I'm still having issues with black. I looked at your change and it looks the same as to what I have. I'm stumped on why when travis runs it it fails but when I run it, well it formats it but my version of black and the one travis uses don't agree.

Can I get an assist again?

Tell me what I'm doing wrong?

I added the test, passes.

**Comment by akrabat** [comment]
I have the same problem with black  as @rawsonj is having.

Travis is showing that black has "reformatted /home/travis/build/rst2pdf/rst2pdf/rst2pdf/flowables.py". However, when I run it locally, that file doesn't change:

```
$ pre-commit run black --files rst2pdf/flowables.py
black....................................................................Passed
```

no change!

However, if I ask black to look at all files:

```
$ pre-commit run black -a
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/extensions/sample.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/sinker.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/directives/aafigure.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/svgimage.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/extensions/fancytitles.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/sphinxnodes.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/dumpstyle.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/basenodehandler.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/genpdftext.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/extensions/preprocess_r2p.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/directives/code_block.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/tests/conftest.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/image.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/rson.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/styles.py
reformatted /Users/rob/Projects/python/rst2pdf/doc/assets/flowables.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/genelements.py
reformatted /Users/rob/Projects/python/rst2pdf/rst2pdf/createpdf.py
All done! ✨ 🍰 ✨
18 files reformatted, 26 files left unchanged.
```

18 files are changed!

Thoughts @stephenfin ?

**Comment by rawsonj** [comment]
@akrabat Yeah, this is the exact same behavior I was seeing on my side, so glad I'm not the only one seeing it.

I'm wondering if it's a black version issue. Is travis running black using an older version?

**Comment by akrabat** [comment]
> I'm wondering if it's a black version issue. Is travis running black using an older version?

@rawsonj This is a good question. Can you add `pip freeze` to the .travis.yml file after the pip install lines so that we can get Travis to tell us all the versions?

**Comment by rawsonj** [comment]
Ok, I give up. I'm pretty sure this is a travis configuration issue but I can't seem to figure out where black is in order to print it's version.

**Comment by akrabat** [comment]
I'm even more confused!

In trying to work out what's going wrong, Black on travis is now generating the same errors as it does locally!

latest Travis: https://travis-ci.org/github/rst2pdf/rst2pdf/jobs/736990000
earlier Travis: https://travis-ci.org/github/rst2pdf/rst2pdf/jobs/736064005

Earlier it was complaining about `rst2pdf/rst2pdf/flowables.py`, and now it's complaining about 18 other files! The 18 files it's complaining about are the same as what I see locally.

**Comment by lornajane** [comment]
Wow, we had a whole selection of problems with the build system, which are all fixed by @akrabat in #940 . I hope this means that you can just apply your original changes and things should "Just Work" without needing any of the black/travis fixes. If you'd like me to rebase the branch and rescue your changes, I can do that, let me know!

**Comment by rawsonj** [comment]
Hi @lornajane, I rebased and removed some of my debugging commits as well. Seeing if I pass the checks now.

**Comment by rawsonj** [comment]
Yay! Thanks @akrabat, @lornajane and @stephenfin !

**Comment by rawsonj** [comment]
@akrabat What's the change you requested here? I did add a test for this, so if that's it can you mark the change complete?

**Comment by rawsonj** [comment]
Yeah, I'd appreciate that. I just checked in whatever black wanted to format to get it to pass, and it passed.

IMO, whatever makes the linter happy is what I usually err on, even if it makes the diff larger. The result is usually more maintainable code in the end.

**Comment by akrabat** [comment]
Rebased against master leaving just the relevant files in the branch.

**Comment by rawsonj** [comment]
Cool, thanks @akrabat, um, how does this get merged?

**Comment by akrabat** [comment]
> Cool, thanks @akrabat, um, how does this get merged?

One of us will review the code to check that I haven't screwed something up and then approve and merge it.

**Review by lornajane — APPROVED** [review]
Looks great! Thanks so much :)

**Review by akrabat — APPROVED** [review]

**Pull request merged**
