### PR TITLE
Resolve a TypeError caused by urlunparse

### LINKED ISSUE #596: rst2pdf executable raises "TypeError: Cannot mix str and non-str arguments"
Since c0ff1fbd62a9e76f5aebfb2b6a72ccfe3a35fd33, it seems that no matter what arguments or input is given the following exception is raised:

```
(rst2pdf.env) $ rst2pdf
Traceback (most recent call last):
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1354, in main
    parser = parse_commandline()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1184, in parse_commandline
    def_baseurl = urlunparse(['file',os.getcwd()+os.sep,'','','',''])
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/urllib/parse.py", line 387, in urlunparse
    _coerce_args(*components))
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

### PR DESCRIPTION
**Pull request by alexwlchan**
Resolves #596; see my comment on that issue for an explanation of the problem and the proposed fix.

### CODE REVIEW

**Comment by akrabat** [comment]
I think this patch requires the `future` import which is part of the 2 to 3 work. I've reverted the master branch to be Python 2, so am I correct in thinking that this needs to be merged to the dev branch?

**Comment by alexwlchan** [comment]
> am I correct in thinking that this needs to be merged to the dev branch

Yep, that seems sensible.

**Comment by akrabat** [comment]
I"m not sure what you want to do with this? If it's to be merged, can you rebase and set it to have `dev` as it's base branch?

**Comment by alexwlchan** [comment]
Oops, I’d forgotten about this. My current focus is getting tests passing on master, so for now I’m going to leave this.

**Pull request closed without merging**
