### PR TITLE
Fix crash when generating footnotes out of order under sphinx

### PR DESCRIPTION
**Pull request by nfraprado**
When using rst2pdf with sphinx, if the document has footnotes and the
footnote definition appears before any of the footnote references, it
crashes with the following error:

```
[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 156, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 587, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 787, in visit_footnote
    fnr = self.footnotedict[id]
KeyError: 'usage-model_id3'
```

This occurs because the footnote tries to set the text for all
references, even the ones that didn't appear yet. Fix this by splitting
the work, so that the footnote sets the text for the references before
it, and let the later references set their text by themselves.

I still haven't run the tests on this, because I'm having some trouble setting it up... But I'm already posting this so it can be reviewed. I did run pre-commit on this, though.

### CODE REVIEW

**Comment by lornajane** [comment]
The automated tests don't seem to think that you broke anything so that's a good start! Can we get a test showing this in action (that would fail without this code change)? That will make sure we don't regress this in future.

(let us know if we can help set up the tests, or just share some examples with us of what didn't work before but does now and we can help turning it into a test)

**Comment by nfraprado** [comment]
I added the input testcase. It should crash rst2pdf before the commit, and work fine after it.

I didn't add the reference pdf because as I said, I'm having trouble setting the test framework up, even though I had it working in the past.

I'm getting `ImportError: cannot import name 'decodestring' from 'base64' (/usr/lib/python3.9/base64.py)`, which is weird because that seems to be part of the standard library... I'm using a virtual environment and followed `CONTRIBUTING.rst`.

Feel free to generate and add the reference pdf on you behalf. Otherwise I'll add it when I get this working.

**Comment by lornajane** [comment]
OK that errror is a Python 3.9 problem that we're looking at (see https://github.com/rst2pdf/rst2pdf/pull/959#issuecomment-751485687), I'll give this a try on my 3.8 platform and the CI systems are still happy so that's always good

**Comment by lornajane** [comment]
[sphinx-footnotes-order.pdf](https://github.com/rst2pdf/rst2pdf/files/5754541/sphinx-footnotes-order.pdf)

Here's the PDF I get on my system. I'm mildly confused though because I can't get the test to fail against master so I'm not exactly sure what I'm doing wrong! Advice welcome if anyone has any thoughts.

**Comment by nfraprado** [comment]
> OK that errror is a Python 3.9 problem that we're looking at (see [#959 (comment)](https://github.com/rst2pdf/rst2pdf/pull/959#issuecomment-751485687)), I'll give this a try on my 3.8 platform and the CI systems are still happy so that's always good

Oh, I didn't notice that issue. Good to know it's a known problem at least. I'll see if I can help with investigating that.

> [sphinx-footnotes-order.pdf](https://github.com/rst2pdf/rst2pdf/files/5754541/sphinx-footnotes-order.pdf)
> 
> Here's the PDF I get on my system. I'm mildly confused though because I can't get the test to fail against master so I'm not exactly sure what I'm doing wrong! Advice welcome if anyone has any thoughts.

So, I'm not able to run pytest, but running sphinx directly on the test folder with `sphinx-build -b pdf . out` yields the same pdf you posted here. Running with my commit reverted, or on master, gives the following output:

```
Running Sphinx v3.4.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
/home/nfraprado/cur/git/rst2pdf/rst2pdf/pdfbuilder.py:417: RemovedInSphinx40Warning: The suffix argument for doc2path() is deprecated.
  targetname = self.env.doc2path(docname, self.outdir, self.out_suffix)
/home/nfraprado/cur/git/rst2pdf/rst2pdf/pdfbuilder.py:417: RemovedInSphinx40Warning: The string style base argument for doc2path() is deprecated.
  targetname = self.env.doc2path(docname, self.outdir, self.out_suffix)
building [pdf]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                                                                                    
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing MyProject... 
index 
resolving references...
done
writing MyProject... 
[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/pdfbuilder.py", line 156, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/pdfbuilder.py", line 587, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/pdfbuilder.py", line 787, in visit_footnote
    fnr = self.footnotedict[id]
KeyError: '_id3'
FAILED
build succeeded.
```

rst2pdf fails but strangely sphinx succeeds, which causes an empty pdf to be generated. Perhaps that's why you can't get the test to fail? And looking through the issues, I think this is #886.

**Comment by lornajane** [comment]
OK, a break to look at something different helped me get my head around this properly and I'm very happy to accept this change.

**Review by lornajane — APPROVED** [review]
Thank you so much for fixing the footnotes!

**Comment by nfraprado** [comment]
Oops, I didn't yet add the pdf reference file to the MR though, sorry! Do I need to create another MR to add it now?

**Comment by lornajane** [comment]
Urgh, I had it locally and didn't push. I'll add it!

**Comment by nfraprado** [comment]
Oh, ok, thanks!

**Pull request merged**
