### PR TITLE
Renaming .txt files to .rst in the '/tests/input' directory

### PR DESCRIPTION
**Pull request by diegofsousa**
Hello everyone, everything good? This is my first contribution to this repository based on issues.

This PR intends to resolve issue #923.

All ".txt" files for input testing have been renamed to ".rst"

### CODE REVIEW

**Comment by akrabat** [comment]
Hey @diegofsousa,

Thanks for this. We aren't the fastest moving project in the world, but I'm confident that at least one of us will review and come back on this by the end of the weekend.

**Comment by diegofsousa** [comment]
Hi @akrabat ,

It's all right. Thank you! :)

**Comment by lornajane** [comment]
Thanks for this. While the build looks like it worked, only 32 tests were run rather than the 297 that are there. Can you update the tests to include the new files please?

**Review by lornajane — CHANGES_REQUESTED** [review]
The rename is fine but we still need to include those tests.

**Comment by diegofsousa** [comment]
Hello @lornajane,
Thanks for the review. I refactored the test settings and ran them.

In all, 296 tests were performed. According to the previous version, there are 297, but I cannot find case number 297. If we count the number of tests reported in the master branch (https://travis-ci.org/github/rst2pdf/rst2pdf/jobs/735964770) , we get the value of 296 as well.

 Could you check?

**Comment by lornajane** [comment]
Could you rebase please? We had to make some other changes for a build failure and that's caused conflicts in this branch. Sorry (and let us know if you would like detailed instructions on the rebase or need any help, I can do that!)

**Comment by akrabat** [comment]
Thanks @diegofsousa. This work is now merged to master via #947.

**Pull request closed without merging**
