### PR TITLE
Update CI versions and only upload assets on failure

### PR DESCRIPTION
**Pull request by akrabat**
We require the tests to pass under Python 3.9 now. Python 3.10 is in early dev, but we should test it, allowing it to fail - which it does!

Also only upload the test output files if they fail as we don't need them if the tests pass. It'd be neater to only upload the failed PDF and log files, but this is a good first step.

Finally, split the install dependencies step to separate the apt installation from the pip one as it makes it easier to diagnose when it fails due to fewer lines to scroll through.

### CODE REVIEW

**Review by lornajane — CHANGES_REQUESTED** [review]
This looks a lot better in the failed uploads handling! But the 3.10 does not even successfully install the dependencies, and causes the build to look "failed". My worry is that we stop reacting to failed builds because they always fail, and miss something important. I'd prefer us to work on 3.10 separately but adopt the other changes here immediately.

**Comment by akrabat** [comment]
>  I'd prefer us to work on 3.10 separately but adopt the other changes here immediately.

3.10 removed.

**Comment by nfraprado** [comment]
Great! This should hopefully fix the issue I had in https://github.com/rst2pdf/rst2pdf/pull/969#issuecomment-753649200 where the upload in itself failed. This way we never fail due to infrastructure errors when the tests aren't already failing.

**Review by lornajane — APPROVED** [review]

**Comment by lornajane** [comment]
Thanks for the quick response :) Definitely need to look at 3.10 sometime but at least we're all green for now.

**Pull request merged**
