### PR TITLE
Remove tests and documentation for kerning

### PR DESCRIPTION
**Pull request by nfraprado**
rst2pdf's kerning feature depended on wordaxe, which is no longer
supported, so remove tests and documentation regarding kerning.

### CODE REVIEW

**Comment by nfraprado** [comment]
Hi, sorry to ask this, but could you please label this and my 2 other pending PRs (936 and 933) as "hacktoberfest-accepted"? That way they immediately count towards the completion of my hacktoberfest challenge and we can take the time to review them without rush. Thanks :)

**Comment by akrabat** [comment]
> Hi, sorry for asking this, but could you please label this and my 2 other pending PRs (936 and 933) as "hacktoberfest-accepted"? That way they immediately count towards the completion of my hacktoberfest challenge and we can take the time to review them without rush. Thanks :)

Reading the rules, your PRs here will be counted as our repositories have the `hacktoberfest` topic:

From: https://hacktoberfest.digitalocean.com/details:

> Your pull requests will count toward your participation if they are in a repository with the `hacktoberfest` topic and once they have been merged, approved by a maintainer or labelled as `hacktoberfest-accepted`.

**Review by akrabat — CHANGES_REQUESTED** [review]
I'm happy to see this tidied up.

Please remove `rst2pdf/tests/reference/test_kerning.pdf` as with no test, it's no longer required. There are also a couple of other references to kerning (one in `manual.rst` and one in `styles.style`) that presumably can also be removed.

**Comment by nfraprado** [comment]
I just force-pushed the commit so that it is only a single clean commit making all the changes, but maybe it makes it harder to review... Let me know if it would be better to make separate commits and only squash them at the end, so I can do it for future changes.

**Review by akrabat — APPROVED** [review]

**Comment by akrabat** [comment]
> I just force-pushed the commit so that it is only a single clean commit making all the changes, but maybe it makes it harder to review... Let me know if it would be better to make separate commits and only squash them at the end, so I can do it for future changes.

Personally, I'm happy to see separate commits which show the thinking of the developer. I'm not adverse to squashing for typos or adding a missed file, but generally, whatever the developer doing the feature is happiest with works for me.

We don't squash on merge though.

**Pull request merged**
