### PR TITLE
Add try/catch for errors such as incorrect title ordering

### PR DESCRIPTION
**Pull request by lornajane**
From #550, catch the exceptions that bubble up so we can explain and exit rather than throwing the traceback. Too much output makes the actual error easy to miss so I hope this helps a little.

Things I would like to add but I'm not sure how:
 * A test that tests the error output so I can put the test from #550 in and check that it keeps doing this
 * The output has strange dots and colons in it, output between consecutive lines in createpdf.... I don't think we should block on this but I would love to know how to tidy it up!

### CODE REVIEW

**Comment by akrabat** [comment]
I think that the best way to address the testing of this is to ensure that this situation results in a non-zero return code which we'll be able to test for when #886 is in place.

**Comment by akrabat** [comment]
The strange dots and colons comes from docutils. This is the Exception when inspected in the debugger:

`'...rst2pdf/tests/input/test_malformed_rst.rst:15: (SEVERE/4) Title level inconsistent:\n\n::\n..'`

We get it twice in the log as docutils logs it and then we do.

**Comment by akrabat** [comment]
I've rebased to pick up #925 now that it's merged to develop. Also updated to set the return code on failure(https://github.com/rst2pdf/rst2pdf/pull/990/commits/e816ad985218d0b919faf074a5dbb338d821beaa), add a test(https://github.com/rst2pdf/rst2pdf/pull/990/commits/3406b7ccdee5c1e61d40bb97c1c48a43d74616dc) and removed the duplicate log entry(https://github.com/rst2pdf/rst2pdf/pull/990/commits/8b460a4fe10ea578f6f99f79638415dd12890670)

The output is much neater now:

```
$ rst2pdf input/test_malformed_rst.rst -o output/test_malformed_rst.pdf
input/test_malformed_rst.rst:15: (SEVERE/4) Title level inconsistent:

::
..
[ERROR] createpdf.py:547 Cannot generate PDF, exiting
```

@lornajane If you could review my changes and don't find anything, then I think this is good to merge.

**Comment by lornajane** [comment]
@akrabat looks great but I can't review "my" pull request officially! Want to review and merge?

**Review by akrabat — APPROVED** [review]
Lorna's changes look good to me and she's happy with my updates.

**Pull request closed without merging**
