### PR TITLE
Fix highlight's linenothreshold for Sphinx >=1.8+ & <2.0

### LINKED ISSUE #721: Sphinx 1.8.0+ changes sphinx-issue168
From Sphinx 1.8.0+, `:linenothreshold: 5` isn't working when defined like this:

```rst

.. highlight:: python
   :linenothreshold: 5

.. code-block:: python
   
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
```

With Sphinx 1.7.9 or lower, this code block has line numbers, but with Sphinx 1.8.0 or higher, it doesn't.

### PR DESCRIPTION
**Pull request by akrabat**
Replace Sphinx's `HighlightLanguageTransform` with our own just for Sphinx versions between 1.8.0 & less than 2.0.0 as these versions have broken the `:linenothreshold:` setting in the `highlight` directive.

This code can be removed when we drop support for Python 2

Fixes #721

### CODE REVIEW

**Comment by akrabat** [comment]
@oz123, @ralsina or @lornajane Any chance of a review on this one?

**Comment by ralsina** [comment]
Not me, totally swamped IRL.

**Comment by akrabat** [comment]
I'm not sure how to write one?

**Comment by oz123** [comment]
> I'm not sure how to write one?

I would probably check the contect of a PDF which has:

```
.. highlight:: python
   :linenothreshold: 5

.. code-block:: python
   
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
   "This has more than 5 lines, so it has linenos"
```

But since this code is supposed to be removed in the next version, I don't mind having this merged as is.

**Comment by akrabat** [comment]
Thanks!

**Pull request merged**
