### PR TITLE
Add a CONTRIBUTING file, update related files (manual, README)

### PR DESCRIPTION
**Pull request by lornajane**
Modern convention has new-developer information in a file called `CONTRIBUTING` so this PR adds that file with relevant information and encouragement and a signpost to the CoC.

Minor changes were made also to update the developers doc to update the language to be more focused and inclusive. I also updated the README with a bit more signposting.

### CODE REVIEW

**Comment by stephenfin** [comment]
This looks good to me. Seems you've got trailing whitespace though. Can you run `pre-commit run -a` and push the changes?

**Review by stephenfin — APPROVED** [review]

**Comment by akrabat** [comment]
I think that the information about pre-commit in DEVELOPERS should be added to the Tips and Tricks section of CONTRIBUTING. Though possibly adding information about how to run it manually using `pre-commit run -a` if you don't install it as a hook.

**Comment by lornajane** [comment]
Do I need to do anything more on this one?

**Review by akrabat — APPROVED** [review]
Thanks. This is really good.

**Comment by akrabat** [comment]
> Do I need to do anything more on this one?

Nope. Thanks for the nudge!

**Pull request closed without merging**
