### PR TITLE
Port tests to use pytest.

### PR DESCRIPTION
**Pull request by normanlorrain**
Addresses #739 and related #835 .  My first PR to this project, so I humbly submit for review.

Many changes here, but almost all consist of moving test code to a new _tests/_ folder, outside the main body of code.  This seems to be a preferred structure for pytest.  Sphinx tests are not active; I'd like to save that for a later PR.

The main change is the new _tests/conftest.py_ file.  This is a pytest plugin that adapts the existing test format to what pytest requires.  I tried to reuse code from _autotest.py_ as much as possible.  There's some dead code here, but again to keep this large PR simple I've deferred that. 

Note: I was initially using Black to auto-format code, so to simplify the PR I reverted some of my commits.  Some output PDF's were also inadvertently committed, so that was fixed too.

To run the tests, 
```
pip install pytest
pytest

```
Tested on Linux Debian (Windows WSL), Python 3.8.1.  Currently 6 tests fail, 267 pass.  Failed tests are due to md5 changes, so might or might not be acceptable.

Not tested under Windows because of underlying test code (_execmgr.py_).

### CODE REVIEW

**Comment by oz123** [comment]
Very impressive! Travis tests fail because of matplotlib version . This needs to be updated to 3.1.2.

**Comment by akrabat** [comment]
I'm a little confused to see changes to the test files themselves. Isn't this a reorganisation of where the files live and what runs the tests?

Also, I'm not sure why single quoted strings have been converted to double quotes and the matplotlib dependency changed?

**Comment by normanlorrain** [comment]
> I'm a little confused to see changes to the test files themselves. Isn't this a reorganisation of where the files live and what runs the tests?
> 
> Also, I'm not sure why single quoted strings have been converted to double quotes and the matplotlib dependency changed?

I'll put the test code back to original state (quote changes, etc.) and the requirements.txt as well.  I think I can just update this PR.

**Comment by normanlorrain** [comment]
I see that I made a mistake with this PR, in basing it on my fork's master branch, rather than a proper, separate branch.

Now that my fork's master has fallen behind the upstream master, I'm having trouble rebasing it.  I'm getting several conflicts, which I haven't figured out yet.  (I ended up doing `git rebase --skip`, but I'm not sure if that loses anything I've added).

I may have to restart, by forking again and recreating this on a proper branch and re-creating the PR.  

I'll leave this for now, waiting for #841 to be complete.

**Comment by akrabat** [comment]
Thanks for your work @normanlorrain. I've just merged #850 where @stephenfin used your approach from here.

**Pull request closed without merging**
