### PR TITLE
Template and fonts fixes

### PR DESCRIPTION
**Pull request by pshchelo**
Fixes issue #601 and failures to load fonts

### CODE REVIEW

**Comment by pshchelo** [comment]
Updated commit message in the second commit with exact error

**Comment by akrabat** [comment]
Thanks @pshchelo. 

Are you able to create a test that fails without the changes applied and then passes when they are?

**Comment by pshchelo** [comment]
@akrabat  haven't looked at how tests are done in the repo yet, but will try to come up with something

**Comment by pshchelo** [comment]
Came out with a test for #601 , working on font loading one.

@akrabat what is your preferred process re git history? Should I add tests to each corresponding commit, or create a separate commits with tests and place them before the commits with fixes in the PR so that you can checkout only tests commits and see that they are failing? Travis will then check that they are working with fixes..

**Comment by akrabat** [comment]
Separate commits please. Order would be convenient, but not strictly necessary.

**Comment by pshchelo** [comment]
tests added, the one for font loading may not be ideal (as the order of files in os.walk is not guaranteed), but is the best I could quickly think of

**Comment by pshchelo** [comment]
@akrabat plz review

I bet the issue with font loading can affect multiple users.
For example, on my Ubuntu 18.04 system there are several installed by default fonts that font loading fails on (log when running with this patch):
```
[WARNING] findfonts.py:81 Error processing /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc                                                                                                                    
[WARNING] findfonts.py:81 Error processing /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc                                                                                                                       
[WARNING] findfonts.py:81 Error processing /usr/share/fonts/opentype/noto/NotoSerifCJK-Bold.ttc                                                                                                                      
[WARNING] findfonts.py:81 Error processing /usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc                                                                                                                   
[WARNING] findfonts.py:81 Error processing /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
```
Depending on the order in which Python's `os.walk` finds fonts this can completely break PDF build w/o this patch if such offending fonts are loaded early enough in the list of discovered fonts, producing PDF of zero size.

**Pull request closed without merging**
