### PR TITLE
Prepare 0.95.1 to support Python 3.4 and 3.5

### LINKED ISSUE #955: latest pip (20.3) cannot install latest rst2pdf (0.93) for python 3.5
**Description of problem**

`rst2pdf-0.93.tar.gz` is actually `0.93.dev0` version. Latest version of `pip` prohibates this mismatch between archive name and metadata.

```bash
$ pip install --no-cache-dir -U rst2pdf
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting rst2pdf
  Downloading rst2pdf-0.93.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.4 MB/s
ERROR: Requested rst2pdf from https://files.pythonhosted.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz#sha256=3af44283ced19030a8286e8f8d71106ca6c78efe4bc95e9af42d678c363efcbc has different version in metadata: '0.93.dev0'

```
**Workaround 1**
Install a previous version of rst2pdf
```bash
$ pip install --no-cache-dir -U "rst2pdf<0.93"
...
Successfully installed rst2pdf-0.91
```
**Workaround 2**
Use a previous version of pip
```
$ pip install "pip<20.3"
$ pip install --no-cache-dir -U rst2pdf
Collecting rst2pdf
  Downloading rst2pdf-0.93.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.0 MB/s
Building wheels for collected packages: rst2pdf
  Building wheel for rst2pdf (setup.py) ... done
  Created wheel for rst2pdf: filename=rst2pdf-0.93.dev0-py3-none-any.whl size=202045 sha256=a44fc1587e942a4667398141b3da33c4d684ebd30a02f01e42b6dbc627376bfe
  Stored in directory: /private/var/folders/1l/fkv5s8cx78183y29mvbrznn40000gn/T/pip-ephem-wheel-cache-1yuvh_c_/wheels/66/4b/5f/5b6b90fa40887d2e044843bada84e4a0e3378ab1a469a3a22c
Successfully built rst2pdf
Installing collected packages: rst2pdf
Successfully installed rst2pdf-0.93.dev0
```

**Workaround 3**
upgrade python in order to use rst2pdf>0.93 , not a aption if you have to use python 3.5 (e.g with debian stretch)

🖥 **Versions**

`python -V` Python 3.5.9
`pip --version` 20.3
rst2pdf 0.93 / 0.93dev0

Which operating system are you using? Mac os / Linux (debian stretch)

### PR DESCRIPTION
**Pull request by akrabat**
pip will not install a Python 3 compatible version of rst2pdf (0.95+) due to classifiers we use in setup.py. This is a hotfix to 0.95, to create 0.95.1 that will allow a valid version of rst2pdf to be installed on older Linuxes that have Python 3.4 or 3.5 as their default.

To provide some level of confidence, I've added CI and have made it pass. I've had to ignore all the vectorpdf tests though as they generate different PDFs on each run and I don't know why. Checking locally, the PDFs created looked the same to me, so 🤷‍♀️. We have removed vectorpdf in 0.98 anyway, so I'm not concerned.

I also back-ported the Inkscape 1.0 fix so that I could test locally where the generated PDF was fine. `test_fancytitles` fails on CI, so I've just ignored it. Again, we've removed Inkscape from 0.98, so it's gone now anyway.

GitHub Actions doesn't support Python 3.4, so I've left Travis in for that one, but it's very very slow.

Fixes #955

### CODE REVIEW

**Comment by akrabat** [comment]
Hmm... I'm not sure I can actually PR this as I don't want to merge it to master! 

This PR is therefore here for review purposes.

**Comment by akrabat** [comment]
Travis build: https://travis-ci.org/github/akrabat/rst2pdf/builds/747506732

**Comment by stephenfin** [comment]
I don't think this should go into `master`. Rather, we should create something like a `stable/0.95` branch. Maybe that's what you're proposing and GitHub just isn't able to identify that? If so, could we do the following?

```
git checkout 0.95
git checkout -b stable/0.95
git push origin stable/0.95
#propose PR
```

**Comment by akrabat** [comment]
That makes sense @stephenfin.

I've created the `stable/0.95` branch from the `0.95` tag.

**Comment by akrabat** [comment]
Looks like 0.95 won't work on Python 3.4 due to the Pillow 6.2 requirement.

**Comment by oz123** [comment]
@akrabat why is Python 3.4 support needed? It's EOL for years now. Python 3.5 also, but some Enterprise linux still have it (although one should be able to install 3.6 from external RPM repositories). I think one can safely remove Python3.4 without hurting anyone.

**Comment by akrabat** [comment]
@oz123 See https://github.com/rst2pdf/rst2pdf/issues/955#issuecomment-737289490. For Debian Stretch, 3.5 is the current version, so supporting that seems wise. I'm not sure if any important distros ship with 3.4 or not, but the restraints in our requirements.txt mean that 3.4 isn't so simple anyway, so I was going to to ignore it.

**Review by stephenfin — APPROVED** [review]
LGTM. Good to have CI etc.

**Comment by lornajane** [comment]
What's the status of this? I think we're aggreed that Python 3.5 is enough, and I see the base of the PR changed for that. It's approved, but not merged, do we have more do to here? (I am not sure how I would test this...)

**Comment by akrabat** [comment]
There's still something weird about the CI for Python 3.5 as it passed before I removed the 3.4 stuff. Merging and releasing anyway as it's better than not having it.

**Comment by stephenfin** [comment]
🥳

**Pull request merged**
