### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by akrabat**
This picks up an update to urllib3 which had a security issue prior to 1.23.

(also updates ReportLab to 3.5.12, but this doesn't seem to be a problem!)

Can only upgrade Sphinx to 1.7.9 because 1.8+ causes failures (See #721 & #722)

### CODE REVIEW

**Comment by oz123** [comment]
@akrabat any idea why is the test failing?

**Comment by akrabat** [comment]
Nope. It passed on my computer...

**Comment by akrabat** [comment]
ah - I can reproduce now - I can't operate pip install!

**Comment by akrabat** [comment]
sphinx-issue168 failure is genuine - `linenothreshold` has stopped working…

**Comment by akrabat** [comment]
I think this is ready to review. In particular, note https://github.com/rst2pdf/rst2pdf/pull/718/commits/6d76e69c3bc494669b1fdb1b3f60598cb31b71f3

**Comment by oz123** [comment]
Awesome works. I wonder one can make the rest less fragile. But I guess that not easy with any other large software project.

**Pull request merged**
