### PR TITLE
Reformat codebase with the Black code formatter

### PR DESCRIPTION
**Pull request by stephenfin**
Now that we've got tests passing consistently on different platforms, it's time to start fixing various bugs and closing feature gaps.
Before we do *that* though, we need to do something about the code style, which is in a somewhat sorry state.
While one should generally avoid applying large, style-only changes to existing code bases because they tend to make a complete mess of our ability to use 'git-blame' and related tools effectively, without this we'd otherwise be fixing this stuff manually for years.
Bite the bullet and run all the code through black [[1][1]] (specifically, `black -S`, to avoid unnecessary conversion of single quotes to double quotes) to address the worst of the issues.
A future change will address the remaining issues like use of wildcard imports and commented out (dead) code.

Note that black defaults to a max line length of 88, not 79 [[2][2]], which means we need to configure flake8 to allow this.

[1]: https://pypi.org/project/black/
[2]: https://black.readthedocs.io/en/stable/the_black_code_style.html

Closes: #724
Closes: #711

### CODE REVIEW

**Comment by akrabat** [comment]
Sorry, @stephenfin  - looks like the python3-ification branch conflicted.

**Comment by stephenfin** [comment]
Rebased

**Comment by akrabat** [comment]
Can we add a note to the DEVELOPERs.rst for the exactly `black` command that a contributor should use in order to format their code before raising the PR?

Also, can we validate that the code is formatted correctly using Travis?

**Comment by akrabat** [comment]
My first guess on a travis check is `black --skip-string-normalization --check rst2pdf`

**Comment by stephenfin** [comment]
Working on it

**Comment by stephenfin** [comment]
This is done now. I integrated pre-commit to automate the process of these locally. Let me know if anything doesn't make sense.

**Pull request merged**
